### ISSUE TITLE
Adding a newsletter archive

### ISSUE THREAD

**Issue by rskikuli** [uracreative/ura.design#1]
We need to add the archive of our newsletter to our website for (a) archiving purposes (b) easy access to the content from Ura team. This is standard practice from many organizations. @marianaballa please assist on this. 

R.S

**Comment by rskikuli** [comment]
@Borisbudini I can't assign or add labels here... Please check.

**Comment by Borisbudini** [comment]
That's a great point @rskikuli.

**Comment by Borisbudini** [comment]
@elioqoshi can you give permissions to all of us here?

**Comment by AnXh3L0** [comment]
@rskikuli You mean the content itself in a specific page or the link for the archive? For the first one, I find it unnecessary because it adds too much manual work, meanwhile for the latter one we can add a link to the footer with the archive contents.

**Comment by rskikuli** [comment]
Not the content, just a link to the archive. Thanks.

**Comment by AnXh3L0** [comment]
The link to the newsletter archive has been added to the footer area.

**Comment by rskikuli** [comment]
thank you @AnXh3L0 . Closing this,
