### ISSUE TITLE
Adapt

### ISSUE THREAD

**Issue by elioqoshi** [uracreative/ura.design#18]

**Comment by ergishkelzeni** [comment]
@elioqoshi For the documentation of Internews' ADAPT, the branding and the podcast part are done. The website needs to be mentioned (one or two paragraphs) and after that, it needs a review from start to finish.

**Comment by elioqoshi** [comment]
@ergishkelzeni Reviewed and proofread a bit. I think this is okay now, thanks! Removed the website part as I don't think it's a critical part of our work.
