### ISSUE TITLE
Remove  Full-stack developer (Identihub) job position

### ISSUE THREAD

**Issue by rskikuli** [uracreative/ura.design#3]
The position of Full-stack developer (Identihub) - ReactJS + Laravel as mentioned on our website (https://ura.design/jobs/full-stack) is not available anymore since we filled the position already. 
Please remove (or even better archive) this page. 
Deadline: 05.07.2018.

**Comment by elioqoshi** [comment]
Done

**Comment by Borisbudini** [comment]
Apparently she added about the 3rd OSD event, but github thought she was referencing this issue
