### ISSUE TITLE
Knowledge sharing for website updates

### ISSUE THREAD

**Issue by rskikuli** [uracreative/ura.design#4]
I would like to make changes directly to the website myself, but I am afraid there is some learning curve involved for this process since I'm not an advanced GitHub pages person. Mariana & Anxhelo can you support me with this?

**Comment by elioqoshi** [comment]
Is this something we can do at the Work Week or is it more urgent?

**Comment by rskikuli** [comment]
Nothing urgent. Just personal development process. I just want to help when small changes are needed.

**Comment by AnXh3L0** [comment]
*@anxhelo attached a* [message](https://chat.ura.design/ura-design/pl/k3666qy5yfnabbink86cfeiu9c) *from @anxhelo*
Test
