### ISSUE TITLE
phpList newsletter registration on our website

### ISSUE THREAD

**Issue by rskikuli** [uracreative/ura.design#5]
Now that we are using an open source newsletter system we need to:

- update the registration link that is featured on the footer of our website;
- find a solution to show the archive page of the old newsletter system and also a mechanism to show the new 

There is an embed code available from our newsletter platform and also a link that sends to the registration page. 

Deadline for implementation: 18.07.2018

**Comment by Borisbudini** [comment]
@LuisTepshi should be assigned here aswell for backend support (if @AnXh3L0 wants to use php)

**Comment by AnXh3L0** [comment]
This has been implemented and is being closed.
