### ISSUE TITLE
Nice website! :)

### ISSUE THREAD

**Issue by ajaygautam** [uracreative/ura.design#6]
Hello,

Very nice website!
Do you mind if I copy over the jekyll stuff from this repo?

Thanks

Ajay

**Comment by AnXh3L0** [comment]
Hi @ajaygautam, 

Yes, you can copy the Jekyll from this repo, just mind the license used for it.

There's plenty of stuff you won't need since it's custom for our website but you can remove them.

**Comment by ajaygautam** [comment]
Sure. Thanks.
By the way - whats the license.
Actually, found the original template for this - https://themeforest.net/item/lavar-portfolio-agency-jekyll-theme/15679321 
Are you using the same?

**Comment by AnXh3L0** [comment]
Hi @ajaygautam,
The license can be found here: https://themeforest.net/licenses/standard
We started with that template as a base but it has been heavily modified, as you can see from the number of commits in the repo.
