### ISSUE TITLE
Use SVG for "We are proud to have worked with" logos.

### ISSUE THREAD

**Issue by theel0ja** [uracreative/ura.design#7]
(or at least `@2x` lol)

**Comment by elioqoshi** [comment]
Thanks for suggesting this! We had some problems when we first added them, might be worth revisiting. cc @AnXh3L0

**Comment by AnXh3L0** [comment]
Thank you @theel0ja. The latest commit (76e5ea1) fixes this.
The clients section now uses SVG-s instead of PNG-s for the logos.
